# prometheus.yml
global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      dns_sd_configs:
      - names:
        - 'tasks.prometheus'
        type: 'A'
        port: 9090
    - job_name: 'node-exporter'
      scrape_interval: 5s
      dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100
      metric_relabel_configs:
        - source_labels: [nodename]
          target_label: hostname
      #static_configs:
       # - targets: ['node-exporter:9100']
    - job_name: 'cadvisor'
      scrape_interval: 5s
      dns_sd_configs:
      - names:
        - 'tasks.cadvisor'
        type: 'A'
        port: 8080
      #static_configs:
      #  - targets: ['cadvisor:8080']
rule_files:
    - "alert.rules"